// Code generated by logcopter-gen; DO NOT EDIT.

package sqlite_regexp

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.go-sqlite-regexp")
